"use client";

import {useState} from "react";
import {ArrowLeft,ArrowRight,Check,CircleDollarSign,CreditCard,Goal,HeartHandshake,LayoutGrid,Sparkles} from "lucide-react";

const categoryNames=["Продукти","Кафе та ресторани","Комуналка","Транспорт","Авто","Здоров’я","Краса","Одяг","Розваги","Підписки","Подарунки","Дім і затишок","Зв’язок та інтернет","Освіта","Подорожі","Спорт","Кишенькові витрати","Домашні улюбленці","Техніка","Інше"];
const categoryColors=["#ff7a66","#f0a94a","#6558e8","#4c91e8","#39495e","#28a879","#e874a6","#8875d1","#ef7d53","#4f73d9","#ec6b87","#a57a5a","#42a7a2","#6574c4","#28a879","#ef7658","#d3a032","#9b6b51","#66717d","#878b86"];
const banks=["monobank","ПриватБанк","ПУМБ","Ощадбанк","Райффайзен Банк","Готівка"];
const goals=[["reserve","Накопичити фінансову подушку"],["travel","Відпустка або подорож"],["purchase","Велика покупка"],["debt_free","Вийти з боргів"],["control","Просто контролювати витрати"],["custom","Своя ціль"]];

export function OnboardingWizard({displayName}:{displayName:string}){
  const [step,setStep]=useState(1),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const [account,setAccount]=useState({name:"Основна картка",bank:"monobank",balance:"",currency:"UAH",color:"#252629"});
  const [period,setPeriod]=useState<"month"|"week">("month"),[goal,setGoal]=useState("control"),[customGoal,setCustomGoal]=useState(""),[partner,setPartner]=useState(""),[username,setUsername]=useState("");
  const [categories,setCategories]=useState(categoryNames.map((name,index)=>({name,color:categoryColors[index],selected:index<8,limit:""})));
  const selectedBank=banks.indexOf(account.bank);
  async function finish(){
    setSaving(true);setError("");
    const response=await fetch("/api/onboarding",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({account:{...account,balance:Number(account.balance)||0},period,categories:categories.filter(item=>item.selected).map(item=>({...item,limit:Number(item.limit)||0})),goal:goal==="custom"?customGoal:goal,partner,username})});
    const result=await response.json();setSaving(false);
    if(!response.ok)return setError(result.error||"Не вдалося завершити налаштування");
    if(result.inviteUrl)await navigator.clipboard.writeText(result.inviteUrl).catch(()=>{});
    window.location.reload();
  }
  return <main className="onboarding-shell"><div className="onboarding-glow"/><section className="onboarding-card"><header className="onboarding-head"><div className="brand"><span className="brand-mark"><CircleDollarSign/></span> rivna</div><div className="step-dots">{[1,2,3,4,5].map(value=><i key={value} className={value<=step?"active":""}/>)}</div><span>{step} / 5</span></header>
    <div className="onboarding-body">
      {step===1&&<div className="wizard-step"><span className="wizard-icon"><CreditCard/></span><small>Вітаємо, {displayName}</small><h1>Додайте перший рахунок</h1><p>Почнемо з картки або готівки. Усе можна змінити пізніше.</p><label>Назва<input value={account.name} onChange={event=>setAccount({...account,name:event.target.value})}/></label><div className="wizard-grid"><label>Поточний баланс<input type="number" inputMode="decimal" value={account.balance} onChange={event=>setAccount({...account,balance:event.target.value})} placeholder="0"/></label><label>Валюта<select value={account.currency} onChange={event=>setAccount({...account,currency:event.target.value})}><option>UAH</option><option>USD</option><option>EUR</option><option>PLN</option></select></label></div><label>Банк</label><div className="wheel-picker" aria-label="Вибір банку">{banks.map((bank,index)=><button type="button" key={bank} className={index===selectedBank?"selected":""} onClick={()=>setAccount({...account,bank})}>{bank}{index===selectedBank&&<Check/>}</button>)}</div><label>Колір картки<input className="color-choice" type="color" value={account.color} onChange={event=>setAccount({...account,color:event.target.value})}/></label></div>}
      {step===2&&<div className="wizard-step centered"><span className="wizard-icon"><LayoutGrid/></span><small>Період планування</small><h1>Як зручніше планувати?</h1><p>Rivna адаптує прогнози та ліміти під ваш ритм.</p><div className="choice-cards"><button className={period==="month"?"selected":""} onClick={()=>setPeriod("month")}><strong>Місяць</strong><small>Класичний бюджет від зарплати до зарплати</small></button><button className={period==="week"?"selected":""} onClick={()=>setPeriod("week")}><strong>Тиждень</strong><small>Короткі цикли та швидший контроль</small></button></div></div>}
      {step===3&&<div className="wizard-step categories-step"><span className="wizard-icon"><LayoutGrid/></span><small>Категорії та ліміти</small><h1>Оберіть важливе</h1><p>Увімкніть потрібні категорії та за бажанням одразу задайте ліміт.</p><div className="onboarding-categories">{categories.map((item,index)=><div key={item.name} className={item.selected?"selected":""}><button type="button" onClick={()=>setCategories(values=>values.map((value,i)=>i===index?{...value,selected:!value.selected}:value))}><i style={{background:item.color}}>{item.selected&&<Check/>}</i><span>{item.name}</span></button><input type="number" inputMode="numeric" disabled={!item.selected} value={item.limit} onChange={event=>setCategories(values=>values.map((value,i)=>i===index?{...value,limit:event.target.value}:value))} placeholder="Ліміт, ₴"/></div>)}</div></div>}
      {step===4&&<div className="wizard-step centered"><span className="wizard-icon"><Goal/></span><small>Головна мета</small><h1>Що для вас найважливіше?</h1><p>Це допоможе Rivna робити підказки доречнішими.</p><div className="goal-options">{goals.map(([value,label])=><button type="button" key={value} className={goal===value?"selected":""} onClick={()=>setGoal(value)}>{label}{goal===value&&<Check/>}</button>)}</div>{goal==="custom"&&<input autoFocus value={customGoal} onChange={event=>setCustomGoal(event.target.value)} placeholder="Опишіть вашу ціль"/>}</div>}
      {step===5&&<div className="wizard-step centered"><span className="wizard-icon"><HeartHandshake/></span><small>Спільний бюджет</small><h1>Планувати разом?</h1><p>Запросіть партнера зараз або пропустіть цей крок.</p><label>Ваш унікальний username<input value={username} onChange={event=>setUsername(event.target.value.toLowerCase().replace(/[^a-z0-9_.-]/g,""))} placeholder="maria"/></label><label>Email або username партнера<input value={partner} onChange={event=>setPartner(event.target.value)} placeholder="partner@example.com або @partner"/></label><div className="invite-note"><Sparkles/> Якщо людина ще не зареєстрована, буде створене invite‑посилання й скопійоване після завершення.</div></div>}
    </div>
    {error&&<div className="form-message error onboarding-error">{error}</div>}
    <footer className="onboarding-actions"><button className="secondary" disabled={step===1||saving} onClick={()=>setStep(value=>value-1)}><ArrowLeft/> Назад</button>{step<5?<button className="primary" disabled={step===1&&!account.name.trim()} onClick={()=>setStep(value=>value+1)}>Продовжити <ArrowRight/></button>:<button className="primary" disabled={saving} onClick={finish}>{saving?"Зберігаємо…":"Почати"} <Check/></button>}</footer>
  </section></main>
}
